#!/bin/bash
# Shows a spinner while another command is running

function shutdown() {
  tput cnorm
}
trap shutdown EXIT

function cursorBack() {
  echo -en "\033[$1D"
}

function spinner() {
  local LC_CTYPE=C

  local pid=$1

  local spin='-\|/'
  local charwidth=1

  local i=0
  tput civis
  while kill -0 $pid 2>/dev/null; do
    local i=$(((i + $charwidth) % ${#spin}))
    printf "%s" "${spin:$i:$charwidth}"

    cursorBack 1
    sleep .1
  done
  tput cnorm
  wait $pid
  return $?
}

("$@") > /dev/null &

spinner $!
